-- =========================
-- EXTENSION
-- =========================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- ROLES & PERMISSIONS
-- =========================
CREATE TABLE roles (
role_id SERIAL PRIMARY KEY,
role_name VARCHAR(50) UNIQUE NOT NULL,
description TEXT,
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
=========================
CREATE TABLE permissions (
permission_id SERIAL PRIMARY KEY,
permission_name VARCHAR(100) UNIQUE NOT NULL,
description TEXT,
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
=========================
CREATE TABLE role_permissions (
id SERIAL PRIMARY KEY,
role_id INT REFERENCES roles(role_id) ON DELETE CASCADE,
permission_id INT REFERENCES permissions(permission_id) ON DELETE CASCADE,
UNIQUE (role_id, permission_id)
);

-- =========================
-- USERS
-- =========================
CREATE TABLE users_info (
id SERIAL PRIMARY KEY,
username varchar()
full_name VARCHAR(150) NOT NULL,
phone VARCHAR(20),
email VARCHAR(100) UNIQUE,
password TEXT NOT NULL,
status VARCHAR(20) DEFAULT 'active',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
id SERIAL PRIMARY KEY,
user_id INT REFERENCES users_info(id) ON DELETE CASCADE,
role_id INT REFERENCES roles(role_id) ON DELETE CASCADE,
UNIQUE (user_id, role_id)
);

-- =========================
-- KYC
-- =========================
CREATE TABLE users_kyc (
kyc_id SERIAL PRIMARY KEY,
user_id INT REFERENCES users_info(id) ON DELETE CASCADE,
national_id VARCHAR(50),
id_type VARCHAR(50),
dob DATE,
address VARCHAR(250),
city VARCHAR(100),
country VARCHAR(50),
id_photo_path VARCHAR(255),
selfie_photo_path VARCHAR(255),
verified BOOLEAN DEFAULT FALSE,
verified_at TIMESTAMP,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- NON-ACCOUNT CUSTOMERS
-- ================================
INSERT INTO p1fchwgbm.ISTMS_INSTR_TXN (
CONTRACT_REF_NO, VERSION_NO, EVENT_SEQ_NO, ISSUING_BRANCH, PAYABLE_BRANCH, PRODUCT_CODE, INSTR_TYPE, INSTR_STAT, INSTR_CCY, INSTR_AMOUNT, INSTR_DATE, INSTR_NO, DD_MICR_NO, AC_BRANCH, AC_NO, AC_CCY, EXCH_RATE, ACY_AMOUNT, LCY_AMOUNT, REL_CUSTOMER, BENEF_NAME, BENEF_ADDR_1, BENEF_ADDR_2, BENEF_ADDR_3, BENEF_ADDR_4, BENEF_ADDR_5,
IDENTIFIER_NAME_1, IDENTIFIER_VALUE_1, IDENTIFIER_NAME_2, IDENTIFIER_VALUE_2, IDENTIFIER_NAME_3, IDENTIFIER_VALUE_3, IDENTIFIER_NAME_4, IDENTIFIER_VALUE_4, IDENTIFIER_NAME_5, IDENTIFIER_VALUE_5, IDENTIFIER_NAME_6, IDENTIFIER_VALUE_6,
NARRATIVE, MAKER_ID, MAKER_DT_STAMP, CHECKER_ID, CHECKER_DT_STAMP, RECORD_STAT, AUTH_STAT, ONCE_AUTH, MOD_NO,
CHARGE_ACCOUNT, CHG_GL, CHG_CCY, CHG_AMT, CHG_IN_ACY, CHG_IN_LCY, CHG_CCY_ACY_RATE, ACY_LCY_RATE, NETTING_IND, TXN_CODE,
MIS_HEAD_1, CHG_GL_1, CHG_CCY_1, CHG_AMT_1, CHG_IN_ACY_1, CHG_IN_LCY_1, CHG_CCY_ACY_RATE_1, ACY_LCY_RATE_1, NETTING_IND_1, TXN_CODE_1,
MIS_HEAD_2, CHG_GL_2, CHG_CCY_2, CHG_AMT_2, CHG_IN_ACY_2, CHG_IN_LCY_2, CHG_CCY_ACY_RATE_2, ACY_LCY_RATE_2, NETTING_IND_2, TXN_CODE_2,
MIS_HEAD_3, CHG_GL_3, CHG_CCY_3, CHG_AMT_3, CHG_IN_ACY_3, CHG_IN_LCY_3, CHG_CCY_ACY_RATE_3, ACY_LCY_RATE_3, NETTING_IND_3, TXN_CODE_3,
MIS_HEAD_4, CHG_GL_4, CHG_CCY_4, CHG_AMT_4, CHG_IN_ACY_4, CHG_IN_LCY_4, CHG_CCY_ACY_RATE_4, ACY_LCY_RATE_4, NETTING_IND_4, TXN_CODE_4,
MIS_HEAD_5, PRINT_STAT, EXPIRY_DATE, PRINT_COPY, PAYABLE_BANK, OFS_ACC, OFS_CCY, OFS_AMOUNT, OFS_BRANCH,
SSN, REISSUED, ORG_DRAFT_NO, REISSUE_REMARKS, REISSUED_DRAFT_NO, SCODE, XREF, TRN_DT,
BEN_ACCOUNT, BEN_CUST, BEN_CCY, DISCOUNT_DAYS,
THEIR_ACC, THEIR_ACC1, THEIR_ACC2, THEIR_ACC3, THEIR_ACC4,
CHG_TYPE, CHG_TYPE1, CHG_TYPE2, CHG_TYPE3, CHG_TYPE4,
WAIVER, WAIVER1, WAIVER2, WAIVER3, WAIVER4,
LCY_CHG_EXCH_RATE, LCY_CHG_EXCH_RATE1, LCY_CHG_EXCH_RATE2, LCY_CHG_EXCH_RATE3, LCY_CHG_EXCH_RATE4,
CHG_DESC, CHG_DESC1, CHG_DESC2, CHG_DESC3, CHG_DESC4,
TXN_TANKED, ISSUER_CODE, COUNTRY_CODE, DELIVERY_MODE, DELIVERY_ADD1, DELIVERY_ADD2, DELIVERY_ADD3, DELIVERY_ADD4,
CHEQUE_NO, PAYOUT_CHG, PAYMENT_MODE, OLD_DD_MICR_NO, REMARKS,
REVAL_FREQ_DAYS, REVAL_FREQ_MONTHS, REVAL_FREQ_YEARS,
OLD_INSTR_NO, BATCH_NO, CHARGE_CCY, REVALIDATED, DUPLICATE, MANUAL_INPUT, TESTKEY,
BENEF_PH_NO, BENEF_ID_NO,
REM_NAME, REM_ADDR_1, REM_ADDR_2, REM_ADDR_3, REM_ADDR_4, REM_PH_NO, REM_ID_NO,
INWARD_TT_REF, TT_PAYMENT_TYPE, CHG_BY_CASH, ISSUE_BANK, IS_PRINTED, CHG_MODE, MULTI_REF_NO, CHEQUE_ISSUE_DATE
)
-- =========================
-- TRANSACTIONS
-- =========================
CREATE TABLE transactions (
id SERIAL PRIMARY KEY,
transaction_ref VARCHAR(64) UNIQUE NOT NULL,
sender_id INT REFERENCES users_info(id),
beneficiary_acc VARCHAR(50),
amount DECIMAL(18,2),
currency VARCHAR(10),
exchange_rate DECIMAL(18,6),
status VARCHAR(20),
channel VARCHAR(20),
external_ref VARCHAR(100),
failure_reason TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP,
completed_at TIMESTAMP
);

-- =========================
-- remittransaction CODE
-- =========================
CREATE TABLE remittance_codes (
id SERIAL PRIMARY KEY,
remit_code VARCHAR(50) UNIQUE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- LOG TABLE
-- =========================
CREATE TABLE log_details (
id SERIAL PRIMARY KEY,
user_id INT,
action VARCHAR(100),
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX idx_txn_ref ON transactions(transaction_ref);
CREATE INDEX idx_sender_id ON transactions(sender_id);
CREATE INDEX idx_status ON transactions(status);

CREATE INDEX idx_username ON users_info(username);
CREATE INDEX idx_user_phone ON users_info(phone);

CREATE INDEX idx_remit_code ON remittance_codes(remit_code);
CREATE INDEX idx_kyc_user ON users_kyc(user_id);
