// Flutter web bootstrap script
// This file is automatically generated by Flutter build
console.log("Flutter.js loaded");

window._flutter = window._flutter || {};
window._flutter.loader = window._flutter.loader || {
  loadEntrypoint: function(entrypointConfig) {
    console.log("Loading Flutter entrypoint...");
    
    // Create a script tag to load main.dart.js
    var script = document.createElement('script');
    script.src = 'main.dart.js';
    script.type = 'application/javascript';
    
    script.onload = function() {
      console.log("Main.dart.js loaded");
      if (entrypointConfig && entrypointConfig.onEntrypointLoaded) {
        entrypointConfig.onEntrypointLoaded({
          initializeEngine: function() {
            console.log("Initializing Flutter engine...");
            return Promise.resolve({
              runApp: function() {
                console.log("Running Flutter app...");
                // This will be handled by main.dart.js
              }
            });
          }
        });
      }
    };
    
    script.onerror = function() {
      console.error("Failed to load main.dart.js");
    };
    
    document.head.appendChild(script);
  }
};